#!/usr/bin/env bash

VERSION="0.4.1"

CONFIGURATION_FILE="${HOME}/.config/bmrc"

# Order of preference for configuration:
# 1st environment variables
# 2nd configuration file
# 3rd script variable

if [[ -z ${BM_SAVE_DIR} ]]; then
	if [[ -r ${CONFIGURATION_FILE} ]]; then
		source ${CONFIGURATION_FILE}

	else
		# create one
		echo "No configuration file. Creating one..."
		cat <<"ENDCONFIGFILE" > ${CONFIGURATION_FILE}
#!/usr/bin/env bash

# Configuration file for bm bookmark manager
# https://github.com/fernandocanizo/bm


# You can also export these variables or set them in the command line to
# temporally change bm behavior

export BM_SAVE_DIR="${HOME}/Dropbox/bmbookmarks"
ENDCONFIGFILE

		BM_SAVE_DIR="${HOME}/Dropbox/bmbookmarks"
	fi
fi

# bookmarks file
BOOKMARKS="${BM_SAVE_DIR}/bookmarks"

# ensure directory for saving bm bookmarks exists
if [[ ! -d ${BM_SAVE_DIR} ]]; then
	mkdir ${BM_SAVE_DIR}
fi

#
# Output usage info
#

usage() {
  cat <<EOF

  Usage: bm [options] [cmd]

  Commands:

    # add a bookmark with the given url, description, and optional tags
    $ bm add <url> [desc] [tag...]

    # open the first bookmark matching <query>
    $ bm open <query>
    $ bm <query>

    # search the bookmarks via full-text <query>
    $ bm search <query>

    # show tags
    $ bm tags

	# list bookmarks available (default action with no parameters)
    $ bm

    # display statistics about the bookmarks
    $ bm stats

  Options:

     -V, --version   output bm version
     -h, --help      output this help information

EOF
}

#
# Add a bookmark
#
#   <url> [description] [tag ...] 
#

save_bookmark() {
  local url=$1
  local desc=$2
  local tags=${@:3}
  echo
  echo "  Added bookmark"
  echo
  echo "    url: $url"
  echo "    description: $desc"
  echo "    tags: $tags"
  echo
  echo "$url|$desc|$tags" >> $BOOKMARKS
}

#
# List all bookmarks
#

list_bookmarks() {
	if [[ ! -r ${BOOKMARKS} ]]; then
		echo "No bookmarks yet. Try saving some with 'bm add <url>'"
		return
	fi

  echo
  cat $BOOKMARKS \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "  \033[36m%s\033[0m\n", $1
      printf "  \033[33m%s\033[0m\n", $2
      printf "  \033[90m%s\033[0m\n\n", $3
    }' \
    | sed 's/http:\/\///'
  echo
}

#
# Search all bookmarks with <query>
#

search_bookmarks() {
  echo
  cat $BOOKMARKS \
    | grep $1 \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "  \033[36m%s\033[0m\n", $1
      printf "  \033[33m%s\033[0m\n", $2
      printf "  \033[90m%s\033[0m\n\n", $3
    }' \
    | sed 's/http:\/\///'
  echo
}

#
# Open first bookmark matching <query>
#

open_bookmark() {
  cat $BOOKMARKS \
    | grep $1 \
    | cut -d '|' -f 1 \
    | xargs open
}

#
# Diplay some statistics about the bookmarks
#

show_statistics() {
  local total_bookmarks=$(cat $BOOKMARKS | wc -l | sed 's/^ *//')
  local total_tags=$(list_tags | wc -l | sed 's/^ *//')

  echo
  echo "    total bookmarks: $total_bookmarks"
  echo "         total tags: $total_tags"
  echo "        top 10 tags: `display_top_ten_tags`"
  echo
}

#
# Output tags.
#

list_tags() {
  cat $BOOKMARKS \
    | cut -f3 -d '|' \
    | tr " " "\n" \
    | sort \
    | uniq -c \
    | sort -nr
}

# 
# Display the 10 most frequently used tags
#

display_top_ten_tags() {
  echo
  printf "%20s  %s\n" count tag
  list_tags \
    | head -10 \
    | awk '{ printf("%20d  %s\n", $1, $2) }'
}


#
# List urls
#

urls() {
  cat $BOOKMARKS \
    | grep "$1" \
    | cut -d '|' -f 1
}


# no args defaults to list bookmarks
if test $# -eq 0; then
  list_bookmarks
  exit
fi

# parse args

while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    -V|--version) echo $VERSION; exit ;;
    -h|--help) usage; exit ;;
    tags) list_tags; exit ;;
    search) search_bookmarks "$@"; exit ;;
    open) open_bookmark "$@"; exit ;;
    add) save_bookmark "$@"; exit ;;
    stats) show_statistics; exit ;;
    *) open_bookmark $arg; exit ;;
  esac
done
